name: Deploy Backend

on:
  push:
    branches: [main, dev, staging]
    paths:
      - "python-backend/**"   # sirf backend folder change hone pe trigger hoga

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Build & Deploy Backend - ${{ github.ref_name }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python-backend

    steps:
      - uses: actions/checkout@v4

      - name: Set environment name
        id: env
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "ENV_NAME=prod" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref_name }}" == "staging" ]; then
            echo "ENV_NAME=staging" >> $GITHUB_OUTPUT
          else
            echo "ENV_NAME=dev" >> $GITHUB_OUTPUT
          fi

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag & push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPO: myapp-${{ steps.env.outputs.ENV_NAME }}-backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPO:latest
          docker push $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPO:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster myapp-${{ steps.env.outputs.ENV_NAME }}-cluster \
            --service myapp-${{ steps.env.outputs.ENV_NAME }}-backend-service \
            --force-new-deployment \
            --region ap-south-1

      - name: Wait for deployment
        run: |
          aws ecs wait services-stable \
            --cluster myapp-${{ steps.env.outputs.ENV_NAME }}-cluster \
            --services myapp-${{ steps.env.outputs.ENV_NAME }}-backend-service \
            --region ap-south-1
